In [2]:
#ndArray
import numpy as np

data = np.random.randn(2,3)
data * 10

#차원 정보를 알려줌
data.shape

#data type을 알려준다.
data.dtype

dtype('float64')

In [3]:
#ndarray 초기화
data1 = [6,1.5,8,0,1]
arr1 = np.array(data1)
arr1

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

arr2.ndim
arr2.dtype

# zeros empty one 등 다양한 방법으로 초기화가 가능하다.
np.zeros(10)
np.zeros((3,6,2))
np.zeros((3,6))
np.empty((3,6,2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [4]:
data = np.random.randn(3,6,2)
np.empty((3,6,2))

#파이썬 range와 비슷
np.arange(4,15)

np.asarray(np.array([1,2,3]))

#타입 설정등
np.ones((3,4),dtype=np.int32)
np.ones((2,2,3))

np.ones_like([2,2])
np.eye(10)
np.ones((3,4),dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [5]:
#스칼라 연산
arr = np.array([[1,2,3],[4,5,6]])
arr

arr * arr
arr - arr

1/arr

arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [6]:
#색인과 슬라이싱!!!(중요하다)

arr = np.arange(10)
arr

arr[5]

print(arr[5:8])

arr[5:8] = 12
arr

arr_slice = arr[5:8]
arr_slice[1] = 12345

#arr_slice라는 것을 변경해도 같이 변경된다. 결국 새롭게 생성하는 것은 없고 단지 레퍼라는 것!!!
arr

#보았는가?
arr_slice[:] = 64
arr

[5 6 7]


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [39]:
#행렬적인 표현
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d
arr2d[2]
arr2d[0][2]

arr2d[0,2]

arr3d = np.array([[[1,2,3],[4,5,6]] ,[[7,8,9],[10,11,12]]])

arr3d[0]

#copy
old_values = arr3d[0].copy()

old_values
arr3d[0] = 42

arr3d
old_values

arr3d[0]= old_values
arr3d[1,0]

arr[1:6]

arr2d
arr2d[:2]
arr2d[:2,:1]

arr2d[1,:2]
arr2d[2,:1]

arr2d
arr2d[2,:1]

arr2d[:2,1:] = 0
arr2d

    

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [59]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

data = np.random.randn(7,4)
data

names == 'Bob'
data[names=='Bob']
data[names=='Bob',2:]
data[names=='Bob',3]

data[ (names!='Bob')]

mask = (names=='Bob') | (names == 'Will')

mask
data[mask]

data[data < 0] = 0

data

data[names != 'Joe'] =7
data



array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.61939991,  0.65312127,  0.30307238,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.30944265,  0.        ,  0.        ,  0.        ],
       [ 0.2074346 ,  0.05575649,  0.        ,  0.60553312]])

In [84]:
#팬시 색인

arr= np.empty((8,4))
arr

for i in range(8):
    arr[i] = i
    
print(arr   )

#이런 것이 팬시 색인인 것인가?
arr[[4,3,2,1]]

arr[[-3,-5,-7]]

arr = np.arange(32).reshape((8,4))

arr[[1,5,7,2],[0,3,1,2]]

print(arr)
arr[[1,5,7,2]][:,[0,3,1,2]]

#arr[[1,5,7,2]][:2,[0,3,1,2]]

#오묘하도다!
arr[np.ix_([1,5,7,2],[0,3,1,2])]


[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [96]:
arr = np.arange(15).reshape((3,5))
arr
arr.T
print(arr)
print(arr.T)
print(np.dot(arr.T,arr) )
arr = np.random.randn(6,3)
arr

np.dot(arr.T,arr)

arr = np.arange(4).reshape((2,2))
print(arr)
print(arr.T)
np.dot(arr.T,arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]
[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


array([[ 4,  6],
       [ 6, 10]])